query PING {
  ping  
}

query PHRASE ($random: Boolean, $date: DateTime, $id: ID) {
  phrase (random: $random, date: $date, id: $id) {
    id
    phrase
    poem {
      id
      uuid
      title
      author {
        id   
        name
      }
    }
  }  
}

query POEM ($uuid: ID!) {
  poem (uuid: $uuid) {
    id
    uuid
    title
    paragraphs
    intro
    kind
    translation
    appreciation
    author {
      id   
      name
    }
  }
}
