query PING {
  ping  
}

query PHRASE ($random: Boolean) {
  phrase (random: $random) {
    id
    phrase
    poem {
      id
      title
      author {
        id   
        name
      }
    }
  }  
}
