query PING {
  ping  
}

query PHRASE ($random: Boolean, $date: DateTime) {
  phrase (random: $random, date: $date) {
    id
    phrase
    poem {
      id
      title
      author {
        id   
        name
      }
    }
  }  
}

query POEM ($uuid: ID!) {
  poem (uuid: $uuid) {
    id
    title
    author {
      id   
      name
    }
  }
}
